workflows:
  android-apk:
    name: Çek Takip Lokal - Android APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
      flutter: stable
    scripts:
      - name: Projeyi Hazırla ve Derle
        script: |
          unzip -o *.zip
          PROJ_DIR=$(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \;)
          cd "$PROJ_DIR"
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"
    publishing:
      email:
        recipients:
          - muhammethamzaanli@gmail.com
        notify:
          success: true
          failure: true
